name: .NET

on:
  push:
    branches: [ '**' ]
    paths-ignore: ['**/*.md']

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - name: Setup PowerShell
      uses: CRFricke/Setup-PowerShell@v1.0.6

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Build Version
      shell: pwsh
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v6.0'
      run: |
        Get-VersionVariables
        Set-ActionVariable "BUILD_VERSION" "$Tag_Version"
        Write-Host "BUILD_VERSION: $Tag_Version"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/CRFricke/index.json
        owner: CRFricke
      env:
          NUGET_AUTH_TOKEN: ${{secrets.USER_PAT}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore /p:Version=$BUILD_VERSION

    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal

    - name: Display Core.UI obj folder contents
      if: ${{ failure() }}
      shell: pwsh
      run: Get-ChildItem -Path Authorization.Core.UI\obj -Name -Recurse
