name: .NET

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Semver Parser
      id:   simver
      uses: apexskier/github-semver-parse@v1.0.2
      with:
        version: "V1.0.0-beta.1+123456"

    - name: Generate Pack Parameters
      run: |
        chcp 65001 #set code page to utf-8
        echo (NUGET_VERSION=${steps.semver.outputs.version}) >> $env:GITHUB_ENV
        echo (ASSEMBLY_VERSION=${steps.semver.outputs.major} + '.' + ${steps.semver.outputs.minor} + '.' + ${steps.semver.outputs.patch}) >> $env:GITHUB_ENV
        echo (FILE_VERSION=${steps.semver.outputs.major} + '.' + ${steps.semver.outputs.minor} + '.' + ${steps.semver.outputs.patch} + "." + $env.GITHUB_RUN_NUMBER) >> $env:GITHUB_ENV

    - name: Show Environment Variables
      run: |
        echo $env.ASSEMBLY_VERSION
        echo $env.FILE_VERSION
        echo $env.NUGET_VERSION

#    - uses: actions/checkout@v2
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 5.0.x
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
