name: Tag

on:
  push:
    tags: ['v*']

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - name: Setup PowerShell
      uses: CRFricke/Setup-PowerShell@v1.0.4

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Build Version
      shell: pwsh
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v6.0'
      run: |
        Get-VersionVariables
        Set-ActionVariable "BUILD_VERSION" "$Tag_Version"
        Write-Host "BUILD_VERSION: $Tag_Version"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/CRFricke/index.json
        owner: CRFricke
      env:
          NUGET_AUTH_TOKEN: ${{secrets.USER_PAT}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore /p:Version=$BUILD_VERSION

    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal

    - name: Create Authorization.Core NuGet package
      run: dotnet pack **/Authorization.Core.csproj --configuration $BUILD_CONFIG --no-build /p:Version=$BUILD_VERSION

    - name: Upload Authorization.Core NuGet package to GitHub
      run: dotnet nuget push "**/CRFricke.Authorization.Core.*.nupkg" --source https://nuget.pkg.github.com/CRFricke/index.json --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Update Authorization.Core References
      run: |
        dotnet remove **/Authorization.Core.UI.csproj reference **/Authorization.Core.csproj
        dotnet add **/Authorization.Core.UI.csproj package CRFricke.Authorization.Core --version $BUILD_VERSION --source https://nuget.pkg.github.com/CRFricke/index.json

    - name: Create Authorization.Core.UI NuGet package
      run: dotnet pack **/Authorization.Core.UI.csproj --configuration $BUILD_CONFIG /p:Version=$BUILD_VERSION

    - name: Upload Authorization.Core.UI NuGet package to GitHub
      run: dotnet nuget push "**/CRFricke.Authorization.Core.UI.*.nupkg" --source https://nuget.pkg.github.com/CRFricke/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
