name: Tag

on:
  push:
    tags: ['v*']

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - name: Setup PowerShell
      uses: CRFricke/Setup-PowerShell@v1.0.8

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Build Version
      shell: pwsh
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v7.0'
      run: |
        Get-VersionVariables
        Set-ActionVariable "BUILD_VERSION" "$Tag_Version"
        Write-Host "BUILD_VERSION: $Tag_Version"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/CRFricke/index.json
        owner: CRFricke
      env:
          NUGET_AUTH_TOKEN: ${{secrets.USER_PAT}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore /p:Version=$BUILD_VERSION

    - name: Install Playwright
      shell: pwsh
      run: ./Authorization.Core.UI.Tests.Integration/bin/Release/net7.0/playwright.ps1 install

    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-build --verbosity normal

    - name: Create NuGet packages
      run: dotnet pack Authorization.Core.NoTests.slnf --configuration $BUILD_CONFIG --no-build /p:Version=$BUILD_VERSION

    - name: Upload NuGet packages to GitHub
      run: dotnet nuget push "**/*.nupkg" --source https://nuget.pkg.github.com/CRFricke/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
